### ISSUE TITLE
Proposition : Add spacing option for DotStepper

### ISSUE THREAD

**Issue by AntoineArt** [imujtaba8488/package_im_stepper#11]
I'd like to change the spacing between the dots in DotStepper but there is no way to do that.
Could you add it, it would be great !
Thank you for your work it is really helpful !

**Comment by imujtaba8488** [comment]
Hi Antoine, 

Thank you for your feedback. It's a wonderful suggestion. I'm adding it as an enhancement for the next release and will keep you posted!

Warm Regards,
**iMujtaba**

**Comment by imujtaba8488** [comment]
Hi Antoine,

The spacing feature along with a number of other new exciting features have been added to the DotStepper in the latest v0.1.2+9 version. Please update your dependency and code. However, beware there were some breaking changes. For more information refer to the examples.

Regards
**iMujtaba**

**Comment by imujtaba8488** [comment]
Feature added.
