### ISSUE TITLE
Animation Repetition in NumberStepper

### ISSUE THREAD

**Issue by mado-bohsali** [imujtaba8488/package_im_stepper#15]
Please advise on how to remove the animation blinking every second.

- Flutter latest version
- Dart latest version

https://user-images.githubusercontent.com/18421260/103992630-150fbb80-519d-11eb-819e-00238c89f58f.mov

**Comment by imujtaba8488** [comment]
Hi Mado,

The issue is already under active consideration. As soon as a fix is available, I will let you know!

Thanks
Mujtaba

**Comment by imujtaba8488** [comment]
Hi Mado,

This is to inform you that the bug has been fixed. The new version will be available on 3rd February, 2021 on pub.dev.

Best Regards,
**iMujtaba**
