### ISSUE TITLE
Couldn't set icons center position 

### ISSUE THREAD

**Issue by ShehanS** [imujtaba8488/package_im_stepper#16]
![image](https://user-images.githubusercontent.com/7454938/104106170-bbf97200-52d9-11eb-8196-bfe9df649095.png)
I cannot set center position. I this support only mobile view

**Comment by imujtaba8488** [comment]
Hi Shehan,

I believe what you mean is that you want the IconStepper to be center aligned. Is that right? 

In order to identify and fix the problem, please provide more information. For example, The platform you are using it on, some code, etc.

Regards
**Mujtaba**

**Comment by ShehanS** [comment]
Yes I need to set IconStepper center position in Scaffold or Container. 
![image](https://user-images.githubusercontent.com/7454938/104112015-650e8f80-530f-11eb-9dc3-18b685ba228c.png)

I tried different codes to set center position but couldn't it as well as there was no any alignment/position parameter in IconStepper. 

Regars
Shehan

**Comment by imujtaba8488** [comment]
Hi Shehan,

The `alignment` property has added to the im_stepper. The latest version will be available on pub.dev on Wednesday, 3rd February, 2021.

Thanks
**iMujtaba**

**Comment by wizard11** [comment]
Hi imujtaba8488 , I am also facing the same issue. I want to center align the widget. When will the next version be released?

**Comment by imujtaba8488** [comment]
Hi wizard11,

The new release v0.1.2+10 will be available on 6th February on pub.dev.

Regards
**iMujtaba**

**Comment by wizard11** [comment]
Hi imujtaba8488, any updates here?

**Comment by imujtaba8488** [comment]
Hi Wizard,

Apologies for the delay. The new version will be available tomorrow on 14th Feb, 2021 on pub.dev. I will keep you posted.

**Comment by meipra** [comment]
Hi @imujtaba8488, any updates for the package?

**Comment by imujtaba8488** [comment]
Hi Wizard and meipra,

This is to update you that in addition to various bug fixes and performance improvements, the alignment property has been added and the new package is now available on pub.dev

https://pub.dev/packages/im_stepper

Thank you for your feedback!
