### ISSUE TITLE
put custom images instead icons?

### ISSUE THREAD

**Issue by Liliana99** [imujtaba8488/package_im_stepper#2]
Hi,

It is possible to put custom images from assets on list on icons?

Thanks,

**Comment by imujtaba8488** [comment]
In a process of doing it. Though, it doesn't seem logical to add images to the IconStepper as the name itself states 'icons'. However, an exact similar widget capable of adding custom images either from Assets or Network shall be added soon. I will update you soon!

**Comment by imujtaba8488** [comment]
The latest version includes **ImageStepper** an exact similar widget as IconStepper, but supports adding custom images either from assets or network.
