### ISSUE TITLE
nullsafe version?

### ISSUE THREAD

**Issue by robertonic** [imujtaba8488/package_im_stepper#22]
I'm using im_stepper but cannot upgrade my app to null safety. Will there be a nullsafe version of im_stepper ?

**Comment by imujtaba8488** [comment]
Hi Robert, 

Thank you for getting in touch. Yes, hopefully by the end of this week. I will keep you posted!

Regards
iMujtaba

**Comment by robertonic** [comment]
Thanks. I look forward to the new version.

**Comment by chrisihoby-dev** [comment]
I also use this library and really liked it. Looking forward to the null safety version

**Comment by imujtaba8488** [comment]
Hi Chrisihoby,

Thank you. The code has already been migrated to null-safety. It will be available in pub.dev on 4th April (Sunday). I will keep you posted!

Regards,
Mujtaba

**Comment by chrisihoby-dev** [comment]
That's great! Thanks Mujtaba!!

**Comment by imujtaba8488** [comment]
Hi Robert, Chrisihoby, and MarceloRab,

It is to inform you guys that the null-safety version is now available on pub.dev. Thank you for your feedback and support. Here's the link: https://pub.dev/packages/im_stepper

Regards
Mujtaba

**Comment by robertonic** [comment]
Mujtaba

Thank you!  I just tried using the new version and it works well.  

Thanks for the excellent and speedy change.

Rob

**Comment by chrisihoby-dev** [comment]
Mujtaba,
Thanks!!, I really appreciate it.🙏

Chris
