### ISSUE TITLE
after flutter upgrade i'm getting error: Error: Method not found: 'NumberStepper.externallyControlled'

### ISSUE THREAD

**Issue by ripesol** [imujtaba8488/package_im_stepper#23]
after flutter upgrade i'm getting error: Error: Method not found: 'NumberStepper.externallyControlled'
also upgraded im_stepper to 0.1.3

**Comment by imujtaba8488** [comment]
Hi repeal,

Thank you for getting in touch. The externallyControlled constructor was removed in the version 0.1.2+10, because a better approach was put in placed. Please review these examples to update your code accordingly: https://pub.dev/packages/im_stepper/example 

Regards,
Mujtaba
