### ISSUE TITLE
NumberStepper  current step change dynamically

### ISSUE THREAD

**Issue by MostafaKhalile** [imujtaba8488/package_im_stepper#3]
trying to use NumberStepper  with a form with validation and cannot find away to change current sctive step dynamicaly

**Comment by MostafaKhalile** [comment]
I think it should be goNext and goPrevious like those in dotStepper Class

**Comment by imujtaba8488** [comment]
Hi,
Can you please provide some code ... and what exactly do u mean by saying 'change dynamically' .. a little more explanation of the issue you are facing.

**Comment by imujtaba8488** [comment]
Hi, 

The issue stands resolved. Simply use the constructor `NumberStepper.externallyControlled() `and you get the `goNext` and `goPrevious` options to control the Stepper from external buttons.

**Comment by MostafaKhalile** [comment]
Thank you for the prompt reply
