### ISSUE TITLE
How to add space between the line-connector and the fixed-dot?

### ISSUE THREAD

**Issue by SittiphanSittisak** [imujtaba8488/package_im_stepper#32]
Now, I created the stepper like this below.
![image](https://user-images.githubusercontent.com/59549741/160341628-87d311e7-126d-48b2-9556-72b75b895861.png)

But my work looks like this below.
![image](https://user-images.githubusercontent.com/59549741/160341809-0f54897f-06ce-47a1-8e43-b926aa909754.png)

I think the DotStepper has the property that should create.
1. The gap between the line connector and the fixed dot creates space.

Like this:
```
Row(
  children: [
    SizedBox(width: gap),
    lineConnectorWidget(),
    SizedBox(width: gap),
  ],
),
```

**Comment by imujtaba8488** [comment]
Line padding has been added. However, is not yet available on pub.dev. Please use ref to this repo directly in your code.
