### ISSUE TITLE
NumberStepper throws an unhandled Exception

### ISSUE THREAD

**Issue by mrishabh72** [imujtaba8488/package_im_stepper#34]
I have placed NumberStepper in a TabBarView and when I switch to the other tab, exception is throw with the following message

`Unhandled Exception: 'package:flutter[/src/widgets/scroll_controller.dart]()': Failed assertion: line 153 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
`
I tried to debug the issue. Found that the problem can be solved by adding a check to _BaseStepperState State in _afterLayout function by wrapping the animateTo function inside an if condition which is 
   ```
if (_controller.hasClients) {
      _controller.animateTo(
      ...
    }
```

**Comment by Mohit-Joshi-dev** [comment]
@mrishabh72  Please share some code implementation, because i just tried and i am not getting the error.
![Screenshot_1650116911](https://user-images.githubusercontent.com/72641368/163677390-c98b874e-5d92-4b7c-8d3f-667584ebfb4c.png)

Thanks.

**Comment by mrishabh72** [comment]
It is hard for me to recreate that issue. Nevertheless its a good practise to put this IF condition. Leaving this to you & closing the issue
