### ISSUE TITLE
Not Conpitable with Flutter 3.0.0

### ISSUE THREAD

**Issue by BLACKCAT25896** [imujtaba8488/package_im_stepper#38]
This package is not compatible for flutter v3.0.0

../../.pub-cache/hosted/pub.dartlang.org/im_stepper-0.1.3/lib/src/first_stepper/core/base_stepper.dart:169:51: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../development/flutter/packages/flutter/lib/src/widgets/binding.dart').
    if (!widget.scrollingDisabled) WidgetsBinding.instance!.addPostFrameCallback(_afterLayout);
<img width="1440" alt="Screenshot 2022-05-24 at 10 40 44 PM" src="https://user-images.githubusercontent.com/18536121/170088171-361631d4-1924-4de4-8010-3ef4f5efe6fb.png">

**Comment by imujtaba8488** [comment]
This should be resolved. If not please open a new issue. @BLACKCAT25896
