### ISSUE TITLE
How can i update the icons of icon-stepper after navigation with buttons outside of the stepper?

### ISSUE THREAD

**Issue by thfr69** [imujtaba8488/package_im_stepper#4]
Explanation:
I use a column with the stepper, a content area and a navigation on the bottom with buttons (forward, backward). How can I update the stepper so that it marks the current icon after navigation?

**Comment by imujtaba8488** [comment]
Hi,

I believe you want the next and previous buttons (which as you said are along the bottom of column) to control the stepping in the stepper. This is similar to the [issue#3](https://github.com/imujtaba8488/package_im_stepper/issues/3) and currently the stepper gives you two options, either to use the built-in next/previous buttons or simply the tapping, to control the stepping. However, what you are requesting works perfectly in 'DotStepper' and will be added to the rest of the steppers soon. 

I will keep you posted. Thank you for your feedback!

**Comment by imujtaba8488** [comment]
Hi, 

The issue stands resolved. Simply use the constructor IconStepper.externallyControlled() and you get the `goNext` and `goPrevious` options to control the Stepper from external buttons.

**Comment by thfr69** [comment]
Many thanks. Your change works perfectly.

**Comment by imujtaba8488** [comment]
Hi thfr69,

At the moment, enabling onTap or next/Previous buttons in externally controlled stepper results in an error. It will be fixed in one of the upcoming releases. I will keep you posted!

Regards,
iMujtaba
