### ISSUE TITLE
Iconstepper with externalControl and tapping 

### ISSUE THREAD

**Issue by thfr69** [imujtaba8488/package_im_stepper#5]
Please can you also provide direct navigation via "tapping" for the constructor IconStepper.externallyControlled? Otherwise there is no way to control certain steps directly.

**Comment by imujtaba8488** [comment]
Hi thfr69,

A new `activeStep` property has been introduced in the `im_stepper` package that gives you access to control steppers in a much easier way including all the three ways: built-in buttons, direct navigation, and externally. 

Please check out the new release [here](https://pub.dev/packages/im_stepper) and examples [here](https://pub.dev/packages/im_stepper/example). Once again, thank you for your feedback!

Warm Regards,
**iMujtaba**
