### ISSUE TITLE
Option to set initial step

### ISSUE THREAD

**Issue by atul-khemka** [imujtaba8488/package_im_stepper#7]
I tried to find option to set initial step in the stepper but couldn't find it.
Can you please provide initial attribute, so that one can set initial step different from step 0.

**Comment by imujtaba8488** [comment]
Hi Atul,

Thank you for your feedback. Please be sure, it will be added in the upcoming **0.1.2+7** release. I will keep you posted!

Meanwhile, if you like, you can check the latest publication about im_stepper package on medium [here](https://imujtaba8488.medium.com/beautiful-page-indicators-and-steppers-with-the-im-stepper-package-8c091cf5364e).

Regards
iMujtaba Nazki

**Comment by imujtaba8488** [comment]
Hi Atul,

The ability to set the initial step and jump to different steps has also been added. Also, a new `activeStep` property has been introduced in the `im_stepper` package that gives you access to control steppers in a much easier way. 

Please check out the new release [here](https://pub.dev/packages/im_stepper) and examples [here](https://pub.dev/packages/im_stepper/example). Once again, thank you for your patience and feedback!

Warm Regards,
**iMujtaba**

**Comment by atul-khemka** [comment]
Hi iMujtaba,

Thank you so much. You are a champ!!!
