### ISSUE TITLE
Previous button icon 

### ISSUE THREAD

**Issue by Mastpollo10** [imujtaba8488/package_im_stepper#8]
setting previous button icon is not working, while next button icon is setting in both

**Comment by imujtaba8488** [comment]
Hi Mast,

Thank you for your feedback. The issue is now scheduled to be fixed in the upcoming release. I will keep you posted!

Regards
iMujtaba

**Comment by imujtaba8488** [comment]
Hi Mast,

The bug has been fixed and a new `activeStep` property has been introduced in the `im_stepper` package that gives you access to create steppers in a much easier way. The ability to set the initial step and jump to different steps has also been added.

Please check out the new release [here](https://pub.dev/packages/im_stepper) and examples [here](https://pub.dev/packages/im_stepper/example). Once again, thank you for your feedback!

Warm Regards,
**iMujtaba**
