### ISSUE TITLE
DotStepper.externallyControlled

### ISSUE THREAD

**Issue by zelliot** [imujtaba8488/package_im_stepper#9]
Hi iMujtaba,

It would be great to get DotStepper.externallyControlled and the ability to use any State Management to change the step e.g. I use GetX.

Cheers

**Comment by imujtaba8488** [comment]
Hi zelliot,

Thank you for your feedback. Please provide a specific example or use-case, so that such a feature can be added to the im_stepper package.

Regards,
iMujtaba

**Comment by zelliot** [comment]
Hi iMujtaba,

Here is the Widget I am DotStepper in:
```
import '../../controller/breadcrumb_controller.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:im_stepper/stepper.dart';

class FooterWidget extends GetWidget<BreadcrumbController> {
  FooterWidget(
      {Key key,
      this.backFunction,
      this.backText,
      this.forwardFunction,
      this.forwardText})
      : super(key: key);

  final Function backFunction;
  final String backText;
  final Function forwardFunction;
  final String forwardText;

  @override
  Widget build(BuildContext context) {
    return Container(
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          ElevatedButton(
            child: Text(
              backText,
            ),
            onPressed: backFunction,
          ),
          Column(children: [
            Obx(() => Text(controller.page.value)),
            DotStepper(
              dotCount: 6,
              fillStep: false,
              indicatorColor: Colors.blue,
              indicatorEffect: IndicatorEffect.jump,
              indicatorType: IndicatorType.contain,
            ),
          ]),
          ElevatedButton(
            child: Text(forwardText),
            onPressed: () {
              controller.step.value++;
              forwardFunction();
            },
          ),
        ],
      ),
    );
  }
}
```

I'm using Get for state management and to control my app's logic. It would be good for DotStepper to either

- Accept a currentStep Property e.g. 
```
DotStepper(
              currentStep: controller.step.value,
              dotCount: 6,
              fillStep: false,
              indicatorColor: Colors.blue,
              indicatorEffect: IndicatorEffect.jump,
              indicatorType: IndicatorType.contain,
            ),
```

or

- Have an external controller e.g. like TextEditingController
```
DotStepper(
              controller: controller.stepController.value,
              dotCount: 6,
              fillStep: false,
              indicatorColor: Colors.blue,
              indicatorEffect: IndicatorEffect.jump,
              indicatorType: IndicatorType.contain,
            ),
```

What do you think?

Cheers!

**Comment by imujtaba8488** [comment]
Hi Zelliot,

Appreciate your time. Based on your explanation, one clarification, please: - 

- Do you suggest a "Jumping Behavior" feature, i.e., as soon as the `controller.stepController.value` value changes, the `DotStepper` should have an option to **jumpTo** to that specific step?

**Note:** If you intend to use StateManagement to set the value of `jumpTo` property **(Not yet available)**, accidentally changing it somewhere else in your code will also update it. 

Nevertheless, adding a `jumpTo` to the `DotStepper` sounds a good enhancement and will help you achieve the same regardless of what State Management you use. 

Regards,
**iMujtaba**

**Comment by zelliot** [comment]
Hi iMujtaba,

I think having a function like that makes sense. I would then use my own state management to store the step and then use the widget function to jump to a specific step.

The only other way I would suggest having it would be to have two function in the widget e.g. goNext() and goPrevious() (or stepNext() & stepPrevious()). This would be instead of having the bool values that you set to true to move forward or back.

Either way works for me.

Best regards,
Elliot

**Comment by imujtaba8488** [comment]
Hi Elliot,

Thank you for your feedback. I am working on it. Expect it in the upcoming release. I will keep you posted!

Warm regards,
**iMujtaba**

**Comment by imujtaba8488** [comment]
Hi Elliot,

A new `activeStep` property has been introduced in the `im_stepper` package that gives you access to create steppers in a much easier way. The ability to set the initial step and jump to different steps has also been added.

Please check out the new release [here](https://pub.dev/packages/im_stepper) and examples [here](https://pub.dev/packages/im_stepper/example). Once again, thank you for your feedback!

Warm Regards,
**iMujtaba**
